#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

clear
echo -e "\n Case setup valid for openfoam v5.0"

echo -e "\n Running blockMesh"
runApplication blockMesh

function run_and_log(){
  # Run a command and redirect it's output to a log file.
  # First argument is the program name (log file name),
  # rest of the arguments contain the string to run the program.

  cmd=$1
  run_commands="${@:2}"
  echo "Running $cmd with command: $run_commands"
  $run_commands &> log."$cmd"
  if [ $? -ne 0 ]; then
    echo "Running $cmd failed, see log."$cmd". Exiting."
    exit 1
  fi
}
run_and_log surfaceFeatures surfaceFeatures
run_and_log decomposePar decomposePar
#run_and_log snappyHexMesh mpirun -np 8 snappyHexMesh -parallel -overwrite
run_and_log snappyHexMesh snappyHexMesh -overwrite

#run_and_log checkMesh mpirun -np 8 checkMesh -latestTime -parallel
run_and_log checkMesh checkMesh -latestTime

# run_and_log postProcess mpirun -np 8 postProcess -time '1:' -parallel
#run_and_log reconstructParMesh reconstructParMesh -latestTime
#run_and_log reconstructParMesh mpirun -np 8 reconstructParMesh -latestTime -parallel
run_and_log reconstructParMesh reconstructParMesh -latestTime
#run_and_log reconstructPar reconstructPar -latestTime
#run_and_log reconstructPar mpirun -np 8 reconstructPar -latestTime -parallel

#echo -e "Running topoSet"
#runApplication topoSet
echo -e "Running splitMesh"
#runApplication splitMeshRegions -cellZones -defaultRegionName surronding_air -overwrite
#run_and_log splitMeshRegions mpirun -np 8 splitMeshRegions -cellZones -defaultRegionName surronding_air -overwrite -parallel
#run_and_log splitMeshRegions mpirun -np 8 splitMeshRegions -parallel -cellZones -defaultRegionName surronding_air
run_and_log splitMeshRegions splitMeshRegions -cellZones -defaultRegionName surronding_air -overwrite -useFaceZones
echo -e "Setting up boundary conditions"
runApplication changeDictionary -region water
rm log.changeDict*
runApplication changeDictionary -region piston
rm log.changeDict*
runApplication changeDictionary -region surronding_air
echo -e "Running solver"
#runApplication chtMultiRegionFoam
#runParallel $(getApplication)
runApplication chtMultiRegionFoam
echo -e "\n
-------------------------------------------------------------------------------
End Simulation"


# mpirun -np 8 chtMultiRegionFoam -parallel
